steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-west1-docker.pkg.dev/microservices-424800/image-registry/products-msv",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-west1-docker.pkg.dev/microservices-424800/image-registry/products-msv",
      ]